import { COLOURS, WORLD } from "../game/GameConfig.ts";
import type { Player } from "../entities/Player.ts";
import type { ComboSystem } from "../systems/ComboSystem.ts";
import type { Boss } from "../entities/Boss.ts";
import type { LocaleStrings } from "../i18n/translations.ts";
import type { LevelConfig } from "../levels/LevelConfig.ts";

const UI = { navy: "#173d72", blue: "#258fe7", sky: "#64cfff", yellow: "#ffd34e", red: "#ff4d67", white: "#ffffff" } as const;
const LAYOUT = { width: 540, height: 960 } as const;
function rounded(ctx: CanvasRenderingContext2D, x: number, y: number, width: number, height: number, radius: number, fill: string, stroke?: string): void { ctx.beginPath(); ctx.moveTo(x + radius, y); ctx.arcTo(x + width, y, x + width, y + height, radius); ctx.arcTo(x + width, y + height, x, y + height, radius); ctx.arcTo(x, y + height, x, y, radius); ctx.arcTo(x, y, x + width, y, radius); ctx.closePath(); ctx.fillStyle = fill; ctx.fill(); if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = 1.5; ctx.stroke(); } }
function text(ctx: CanvasRenderingContext2D, value: string, x: number, y: number, size: number, color: string, align: CanvasTextAlign = "left", weight = 800): void { ctx.fillStyle = color; ctx.font = `${weight} ${size}px Segoe UI, sans-serif`; ctx.textAlign = align; ctx.textBaseline = "middle"; ctx.fillText(value, x, y); }
function bar(ctx: CanvasRenderingContext2D, x: number, y: number, width: number, value: number, color: string): void { rounded(ctx, x, y, width, 8, 4, "rgba(19,61,114,.16)"); rounded(ctx, x, y, Math.max(0, width * value), 8, 4, color); }

export function drawHUD(ctx: CanvasRenderingContext2D, player: Player, score: number, combo: ComboSystem, boss: Boss, runTime: number, copy: LocaleStrings, level: LevelConfig): void {
  const scale = Math.min(WORLD.width / LAYOUT.width, WORLD.height / LAYOUT.height);
  ctx.save(); ctx.translate((WORLD.width - LAYOUT.width * scale) / 2, (WORLD.height - LAYOUT.height * scale) / 2); ctx.scale(scale, scale);
  rounded(ctx, 14, 14, 176, 68, 18, "rgba(255,255,255,.9)", "rgba(255,255,255,.75)"); text(ctx, copy.hud.hull, 28, 34, 9, UI.navy); text(ctx, `${Math.ceil(player.hp)} / ${player.maxHp}`, 175, 34, 9, UI.navy, "right"); bar(ctx, 28, 43, 146, player.hp / player.maxHp, player.hp < player.maxHp * .25 ? UI.red : UI.yellow); text(ctx, copy.hud.shield, 28, 63, 9, UI.blue); text(ctx, `${Math.ceil(player.shield)}`, 175, 63, 9, UI.blue, "right"); bar(ctx, 28, 70, 146, player.maxShield ? player.shield / player.maxShield : 0, UI.sky);
  rounded(ctx, LAYOUT.width - 160, 14, 146, 68, 18, "rgba(255,255,255,.9)", "rgba(255,255,255,.75)"); text(ctx, copy.hud.score, LAYOUT.width - 28, 33, 9, UI.blue, "right"); text(ctx, score.toLocaleString("en-US"), LAYOUT.width - 28, 55, 21, UI.navy, "right", 900); if (combo.count >= 2) { rounded(ctx, LAYOUT.width - 106, 71, 92, 25, 11, UI.yellow); text(ctx, `${copy.hud.combo} ×${combo.count}`, LAYOUT.width - 60, 84, 9, UI.navy, "center", 900); }
  if (boss.active && !boss.destroyed) { rounded(ctx, LAYOUT.width / 2 - 130, 101, 260, 38, 15, "rgba(255,255,255,.9)"); text(ctx, `${boss.displayName} · ${copy.hud.phase} ${boss.phase}`, LAYOUT.width / 2, 113, 9, UI.red, "center", 900); bar(ctx, LAYOUT.width / 2 - 104, 121, 208, boss.hp / boss.maxHp, UI.red); }
  else { rounded(ctx, LAYOUT.width / 2 - 130, 101, 260, 35, 15, "rgba(255,255,255,.86)"); text(ctx, `${copy.level.level} ${level.level} · ${level.name}`, LAYOUT.width / 2, 114, 9, UI.navy, "center", 900); text(ctx, `${copy.hud.altitude} ${Math.floor(runTime * 83).toString().padStart(5, "0")}`, LAYOUT.width / 2, 127, 7, UI.blue, "center", 700); }
  const ultimateY = LAYOUT.height - 34; rounded(ctx, 18, ultimateY - 28, LAYOUT.width - 36, 20, 10, "rgba(255,255,255,.78)"); bar(ctx, 24, ultimateY - 22, LAYOUT.width - 48, player.ultimate / 100, player.ultimate >= 100 ? COLOURS.violet : UI.sky); text(ctx, player.ultimate >= 100 ? copy.hud.ultimateReady : copy.hud.ultimate, 26, ultimateY - 40, 9, UI.white); if (player.ultimate >= 100) text(ctx, copy.hud.activate, LAYOUT.width - 110, ultimateY - 40, 9, UI.yellow, "right", 900); const buttonY = LAYOUT.height - 160; rounded(ctx, LAYOUT.width - 78, buttonY, 56, 56, 20, player.ultimate >= 100 ? UI.yellow : "rgba(255,255,255,.8)", "rgba(255,255,255,.9)"); text(ctx, "⚡", LAYOUT.width - 50, buttonY + 28, 23, player.ultimate >= 100 ? UI.navy : UI.blue, "center", 900); ctx.restore();
}
export function ultimateButtonContains(x: number, y: number): boolean { const scale = Math.min(WORLD.width / LAYOUT.width, WORLD.height / LAYOUT.height); const layoutX = (x - (WORLD.width - LAYOUT.width * scale) / 2) / scale; const layoutY = (y - (WORLD.height - LAYOUT.height * scale) / 2) / scale; return layoutX > LAYOUT.width - 94 && layoutX < LAYOUT.width - 6 && layoutY > LAYOUT.height - 176 && layoutY < LAYOUT.height - 88; }
