import type { EnemyType } from "../game/types.ts";
import type { Environment, Formation, LevelConfig, LevelPalette, Objective, SpawnDirection, WaveConfig } from "./LevelConfig.ts";

const PALETTES: Record<Environment, LevelPalette> = {
  stratosphere: { top: "#082b47", middle: "#176787", bottom: "#e68b52", accent: "#62f4ff", secondary: "#ffb45f", cloud: "#b8f3ff" }, sunset: { top: "#32104d", middle: "#b33767", bottom: "#ff9b54", accent: "#ffdf78", secondary: "#ff5da2", cloud: "#ffc6b4" }, storm: { top: "#101737", middle: "#344488", bottom: "#14213e", accent: "#9d8cff", secondary: "#66f5ff", cloud: "#7686b8" }, nebula: { top: "#190c36", middle: "#552a83", bottom: "#07162d", accent: "#cf78ff", secondary: "#5dffc8", cloud: "#d89dff" }, night: { top: "#020711", middle: "#061a2d", bottom: "#03050a", accent: "#55a8ff", secondary: "#ff4d78", cloud: "#18344b" }, asteroid: { top: "#261718", middle: "#55342c", bottom: "#100d13", accent: "#ff9b54", secondary: "#e6d08b", cloud: "#72524d" }, tunnel: { top: "#071414", middle: "#123c3c", bottom: "#030909", accent: "#5dffc8", secondary: "#ffd75d", cloud: "#214b49" }, warp: { top: "#16072f", middle: "#063867", bottom: "#020611", accent: "#9d76ff", secondary: "#52f7ff", cloud: "#384d97" }, armada: { top: "#241010", middle: "#5d202d", bottom: "#09070c", accent: "#ff665d", secondary: "#ffd05d", cloud: "#6f3947" }, void: { top: "#010103", middle: "#10051d", bottom: "#000000", accent: "#ffffff", secondary: "#ff365f", cloud: "#22162f" },
};

const ENEMY_DENSITY_MULTIPLIER = 2.5;
const wave = (id: string, formation: Formation, enemyTypes: EnemyType[], count: number, rows = 1, direction: SpawnDirection = "top", bulletPatterns?: WaveConfig["bulletPatterns"], gap = 0.85): WaveConfig => ({ id, formation, enemyTypes, count, rows, direction, bulletPatterns, gap, spawnInterval: 0.35, burst: 1 });
const level = (id: number, name: string, identity: string, environment: Environment, objective: Objective, _baseEnemyTarget: number, _baselineActiveEnemies: number, activeShooterLimit: number, shooterRatio: number, enemyTypes: EnemyType[], waves: WaveConfig[], overrides: Partial<LevelConfig> = {}): LevelConfig => {
  // Every authored enemy can coexist in the scene; the formation schedule is
  // now driven by encounter design rather than a same-screen safety ceiling.
  const sustainedWaves = waves.map((entry) => ({ ...entry, count: Math.ceil(entry.count * ENEMY_DENSITY_MULTIPLIER) }));
  const totalEnemyTarget = sustainedWaves.reduce((total, entry) => total + entry.count, 0);
  return {
    level: id, name, identity, environment, objective, totalEnemyTarget, waveCount: sustainedWaves.length, maxActiveEnemies: totalEnemyTarget, activeShooterLimit, shooterRatio, enemyTypes, waves: sustainedWaves, duration: objective === "boss" ? 110 : 72 + id * 2, minimumDuration: 30, difficulty: Number((1 + (id - 1) * 0.15).toFixed(2)), enemyRows: id >= 8 ? 3 : id >= 3 ? 2 : 1, waveGapMin: 0, waveGapMax: 0, preSpawnThreshold: 0, bulletPatterns: ["single"], hazards: [], maxOnScreen: totalEnemyTarget, rewardTier: Math.ceil(id / 2), damageMultiplier: 1 + (id - 1) * 0.04, movementMultiplier: 1 + (id - 1) * 0.022, palette: PALETTES[environment], ...overrides,
  };
};

export const MAX_LEVEL = 10;

export const LEVELS: LevelConfig[] = [
  level(1, "FIRST CONTACT", "Continuous single-shot formations establish the first combat rhythm.", "stratosphere", "destroy", 30, 6, 2, 0.65, ["scout", "shooter"], [
    wave("line", "line", ["scout", "shooter"], 5), wave("v", "v", ["shooter", "scout"], 6), wave("stagger", "diagonal", ["scout", "shooter"], 5), wave("split", "pincer", ["shooter", "scout"], 6, 1, "sides"), wave("climax", "wave", ["shooter", "scout"], 8),
  ], { duration: 65, enemyRows: 1 }),
  level(2, "FORMATION ATTACK", "Line, V, diagonal and double-column formations overlap without empty downtime.", "sunset", "destroy", 36, 7, 3, 0.70, ["scout", "shooter", "interceptor"], [
    wave("line", "line", ["scout", "shooter"], 5), wave("v", "v", ["shooter", "scout"], 6), wave("diagonal", "diagonal", ["scout", "shooter"], 5), wave("column", "line", ["shooter", "interceptor"], 6, 2), wave("split", "pincer", ["interceptor", "shooter"], 6, 1, "sides"), wave("finish", "v", ["shooter", "scout"], 8, 2, "top", ["double"]),
  ], { duration: 68, enemyRows: 2, bulletPatterns: ["single", "double"] }),
  level(3, "DOUBLE FRONT", "Two-row fronts create depth while triple shots remain rare and readable.", "nebula", "destroy", 42, 8, 3, 0.70, ["scout", "shooter"], [
    wave("front-a", "line", ["scout", "shooter"], 6, 2), wave("front-b", "v", ["shooter", "scout"], 6, 2), wave("diagonal", "diagonal", ["shooter", "scout"], 5, 2), wave("double-v", "v", ["shooter", "scout"], 6, 2), wave("cross", "cross", ["scout", "shooter"], 6, 2, "sides"), wave("pressure", "wave", ["shooter", "scout"], 6, 2, "top", ["triple"]), wave("close", "line", ["shooter", "scout"], 7, 2),
  ], { duration: 72, bulletPatterns: ["single", "double", "triple"] }),
  level(4, "CROSSFIRE", "Warning-marked side entries combine with top formations for controlled crossfire.", "armada", "destroy", 48, 9, 4, 0.75, ["scout", "shooter", "interceptor"], [
    wave("top", "line", ["scout", "shooter"], 6, 2), wave("left-right", "pincer", ["interceptor", "shooter"], 7, 2, "sides"), wave("v", "v", ["shooter", "scout"], 6, 2), wave("cross", "cross", ["interceptor", "shooter"], 7, 2, "sides", ["double"]), wave("diagonal", "diagonal", ["shooter", "scout"], 7, 2, "top", ["triple"]), wave("pincer", "pincer", ["interceptor", "shooter"], 7, 2, "sides"), wave("climax", "wave", ["shooter", "scout"], 8, 2, "top", ["triple"]),
  ], { duration: 76, bulletPatterns: ["single", "double", "triple"] }),
  level(5, "FIRST BOSS", "Eight dense waves lead directly into the Heavy Gunship warning and encounter.", "storm", "boss", 48, 9, 4, 0.75, ["scout", "shooter", "interceptor"], [
    wave("screen-a", "line", ["scout", "shooter"], 6, 2), wave("screen-b", "v", ["shooter", "scout"], 6, 2), wave("sides", "pincer", ["interceptor", "shooter"], 5, 2, "sides"), wave("double", "line", ["shooter", "scout"], 6, 2), wave("diagonal", "diagonal", ["shooter", "interceptor"], 6, 2), wave("heavy-a", "wave", ["shooter", "scout"], 7, 2, "top", ["triple"]), wave("heavy-b", "cross", ["interceptor", "shooter"], 6, 2, "sides"), wave("last-screen", "v", ["shooter", "scout"], 6, 2),
  ], { miniBoss: "heavy-gunship", bossHealthMultiplier: 1.5, bulletPatterns: ["single", "double", "triple"], duration: 108 }),
  level(6, "AIR SUPERIORITY", "Two-row formations and fixed-lock dive bombers establish the midgame.", "nebula", "destroy", 60, 10, 5, 0.80, ["scout", "shooter", "diveBomber"], [
    wave("rank-a", "line", ["scout", "shooter"], 7, 2), wave("rank-b", "v", ["shooter", "scout"], 7, 2), wave("dive-a", "diagonal", ["diveBomber", "shooter"], 8, 2), wave("rank-c", "wave", ["shooter", "scout"], 7, 2), wave("dive-b", "pincer", ["diveBomber", "shooter"], 8, 2, "sides"), wave("three-row", "line", ["scout", "shooter", "diveBomber"], 7, 3), wave("pressure", "v", ["shooter", "diveBomber"], 8, 2, "top", ["triple"]), wave("finish", "wave", ["shooter", "scout"], 8, 2),
  ], { duration: 80, bulletPatterns: ["single", "double", "triple"] }),
  level(7, "BULLET PRESSURE", "Sustained fire exposes three to five attack sources while five-way shots stay scarce.", "night", "destroy", 66, 11, 5, 0.80, ["scout", "shooter", "diveBomber", "gunship"], [
    wave("opening", "line", ["shooter", "scout"], 7, 2), wave("dive", "v", ["diveBomber", "shooter"], 7, 2), wave("double", "line", ["shooter", "scout"], 8, 2), wave("gunship-a", "wave", ["gunship", "shooter"], 7, 2, "top", ["five"]), wave("sides", "pincer", ["diveBomber", "shooter"], 8, 2, "sides"), wave("pressure", "v", ["shooter", "scout"], 7, 2, "top", ["triple"]), wave("gunship-b", "cross", ["gunship", "shooter"], 7, 2, "sides", ["five"]), wave("dive-close", "diagonal", ["diveBomber", "shooter"], 8, 2), wave("finish", "wave", ["shooter", "scout"], 7, 2),
  ], { duration: 84, bulletPatterns: ["single", "double", "triple", "five"] }),
  level(8, "HEAVY ASSAULT", "Three-row assaults mix fast dives with durable heavy gunships under a six-shooter cap.", "storm", "destroy", 72, 12, 6, 0.85, ["scout", "shooter", "diveBomber", "gunship"], [
    wave("rank-a", "line", ["shooter", "scout"], 8, 2), wave("dive-a", "v", ["diveBomber", "shooter"], 8, 2), wave("heavy-a", "wave", ["gunship", "shooter"], 8, 2, "top", ["triple"]), wave("three-a", "line", ["scout", "shooter", "diveBomber"], 8, 3), wave("sides", "pincer", ["diveBomber", "shooter"], 8, 2, "sides"), wave("heavy-b", "cross", ["gunship", "shooter"], 8, 2, "sides", ["triple"]), wave("three-b", "v", ["shooter", "scout", "diveBomber"], 8, 3), wave("dive-b", "diagonal", ["diveBomber", "shooter"], 8, 2), wave("climax", "wave", ["gunship", "shooter", "scout"], 8, 3, "top", ["five"]),
  ], { duration: 88, bulletPatterns: ["single", "double", "triple", "five"] }),
  level(9, "ELITE DEFENSE", "Seven continuous formation waves, a paced elite section and a final heavy assault.", "armada", "destroy", 78, 13, 6, 0.85, ["scout", "shooter", "gunship", "elite"], [
    wave("screen-a", "line", ["shooter", "scout"], 8, 2), wave("screen-b", "v", ["shooter", "gunship"], 8, 2), wave("screen-c", "wave", ["scout", "shooter"], 8, 2), wave("screen-d", "pincer", ["gunship", "shooter"], 8, 2, "sides"), wave("screen-e", "line", ["shooter", "scout"], 8, 3), wave("screen-f", "v", ["gunship", "shooter"], 8, 2, "top", ["triple"]), wave("elite", "line", ["elite", "shooter"], 8, 2, "top", ["five"]), wave("heavy-a", "wave", ["gunship", "shooter"], 8, 3), wave("heavy-b", "cross", ["elite", "shooter"], 14, 3, "sides", ["five"]),
  ], { duration: 94, bulletPatterns: ["single", "double", "triple", "five", "tracking"] }),
  level(10, "FINAL MISSION", "Four combat acts lead into OMEGA after a short warning transition.", "void", "boss", 80, 14, 7, 0.90, ["scout", "shooter", "diveBomber", "gunship", "elite", "sniper"], [
    wave("part1-a", "line", ["scout", "shooter"], 5, 2), wave("part1-b", "v", ["shooter", "scout"], 5, 2), wave("part1-c", "diagonal", ["shooter", "scout"], 5, 2), wave("part1-d", "pincer", ["shooter", "diveBomber"], 5, 2, "sides"), wave("part2-a", "line", ["gunship", "shooter"], 5, 2, "top", ["triple"]), wave("part2-b", "wave", ["diveBomber", "shooter"], 5, 2), wave("part2-c", "cross", ["gunship", "shooter"], 5, 2, "sides", ["triple"]), wave("part2-d", "v", ["diveBomber", "gunship"], 5, 2), wave("part3-a", "line", ["elite", "shooter"], 4, 2, "top", ["five"]), wave("part3-b", "v", ["elite", "sniper"], 4, 2), wave("part3-c", "wave", ["elite", "shooter"], 4, 2, "top", ["five"]), wave("part3-d", "cross", ["elite", "sniper"], 4, 2, "sides", ["tracking"]), wave("part4-a", "line", ["shooter", "gunship", "scout"], 6, 3), wave("part4-b", "pincer", ["diveBomber", "shooter", "elite"], 6, 3, "sides"), wave("part4-c", "wave", ["gunship", "shooter", "sniper"], 6, 3, "top", ["five"]), wave("part4-d", "v", ["elite", "shooter", "diveBomber"], 6, 3, "top", ["triple"]),
  ], { boss: "omega", bossHealthMultiplier: 1.6, duration: 130, bulletPatterns: ["single", "double", "triple", "five", "wave", "tracking"] }),
];

export function getLevel(levelNumber: number): LevelConfig { return LEVELS[Math.max(0, Math.min(MAX_LEVEL - 1, levelNumber - 1))]; }
